# Generated by Django 5.2.5 on 2025-08-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, unique=True, verbose_name="Nome"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[("PF", "Pessoa Física"), ("PJ", "Pessoa Jurídica")],
                        default="PF",
                        max_length=2,
                        verbose_name="Tipo de Cliente",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque essa opção caso o cliente cancele o serviço.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "alarme",
                    models.BooleanField(
                        default=False,
                        help_text="Marque essa opção caso o serviço de monitoramento por alarme tenha sido contratado.",
                        verbose_name="Alarme",
                    ),
                ),
                (
                    "camera",
                    models.BooleanField(
                        default=False,
                        help_text="Marque essa opção caso o serviço de monitoramento por câmeras tenha sido contratado.",
                        verbose_name="Câmera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome", "ativo"],
                "indexes": [models.Index(fields=["nome"], name="idx_cliente_nome")],
            },
        ),
    ]
